export enum Repositories {
    REQUEST_LOGS = 'REQUEST_LOGS_REPOSITORY',
    APPLICATION_LOGS = 'APPLICATION_LOGS_REPOSITORY',
    ERRORS = 'ERRORS_REPOSITORY',
    TRAFFIC_METRICS = 'TRAFFIC_METRICS_REPOSITORY',
    RESOURCES = 'RESOURCES_REPOSITORY',
}
