export enum Routes {
    DOCS = 'docs',
    QUEUES = 'queues',
    USERS = 'users',
    AUTH = 'auth',
    AUTH_GOOGLE = 'auth/google',
    TEAMS = 'teams',
    TEAM_MEMBERS = 'teams/:teamId/members',
    APPS = 'apps',
    ENDPOINTS = 'apps/:appId/endpoints',
    CONSUMERS = 'apps/:appId',
    GEO_IP = 'geo-ip',
    REQUEST_LOGS = 'request-logs',
    RESOURCES = 'resources',
    INGESTION = 'ingest',
}
