// This file is auto-generated by @hey-api/openapi-ts

export type AlertFilterItem = {
    id: number;
    name: string;
};

export type AlertRuleApp = {
    id: number;
    name: string;
    slug: string;
};

export type AlertRuleAppEnv = {
    id: number;
    name: string;
    slug: string;
    online: boolean;
    order?: number;
};

export type AlertRuleFilter = {
    id: number;
    name: string;
};

export type AlertRuleFilters = {
    consumer: (AlertRuleFilter | null);
    consumer_group: (AlertRuleFilter | null);
    method: (string | null);
    path: (string | null);
    status_code: (string | null);
};

export type AlertRuleTimelineChartDataset = {
    timestamps: Array<string>;
    values: Array<number>;
};

export type AnnouncementResponseItem = {
    id: number;
    severity: 'info' | 'warning' | 'critical';
    title: (string | null);
    message: string;
};

export namespace AnnouncementResponseItem {
    export enum severity {
        INFO = 'info',
        WARNING = 'warning',
        CRITICAL = 'critical'
    }
}

export type ApdexScoreChartDataset = {
    time_windows: Array<string>;
    apdex_scores: Array<(number | null)>;
    total_request_counts: Array<number>;
};

export type AppEnvItem = {
    id: number;
    name: string;
    slug: string;
    liveness_check_enabled: boolean;
    health_check_enabled: boolean;
    health_check_url: (string | null);
    endpoint_count: number;
    client: (string | null);
    versions: ({
    [key: string]: string;
} | null);
    last_sync_at: (string | null);
    last_startup_at: (string | null);
    online: boolean;
    active: boolean;
    instance_count?: (number | null);
};

export type ApplicationLogItem = {
    timestamp: string;
    message: string;
    level: (string | null);
    logger: (string | null);
    file: (string | null);
    line: (number | null);
};

export type ConfigureMicrosoftTeamsIntegrationRequestBody = {
    webhook_url: string;
};

export type ConfigureSentryIntegrationRequestBody = {
    org: (string | null);
};

export type ConsumerGroupItem = {
    id: number;
    name: string;
};

export type ConsumersChartDataset = {
    consumer_status: 'New' | 'Existing';
    time_windows: Array<string>;
    consumer_counts: Array<number>;
};

export namespace ConsumersChartDataset {
    export enum consumer_status {
        NEW = 'New',
        EXISTING = 'Existing'
    }
}

export type ConsumersItem = {
    id: number;
    name: string;
};

export type CPUMemoryChartDataset = {
    time_windows: Array<string>;
    cpu_percent_avgs: Array<(number | null)>;
    cpu_percent_mins: Array<(number | null)>;
    cpu_percent_maxs: Array<(number | null)>;
    memory_rss_avgs: Array<(number | null)>;
    memory_rss_mins: Array<(number | null)>;
    memory_rss_maxs: Array<(number | null)>;
};

export type CreateAlertRuleRequestBody = {
    name: string;
    description?: (string | null);
    metric: string;
    condition: string;
    threshold: number;
    threshold_unit?: (string | null);
    period_minutes: number;
    frequency_minutes?: (number | null);
    cron_expression?: (string | null);
    timezone?: (string | null);
    notify_triggered_after_minutes?: number;
    notify_resolved_after_minutes?: number;
    filter_consumer_id?: (number | null);
    filter_consumer_group_id?: (number | null);
    filter_method?: (string | null);
    filter_path?: (string | null);
    filter_status_code?: (string | null);
    app_env_id: number;
};

export type CreateAlertRuleResponse = {
    id: number;
};

export type CreateApiKeyResponse = {
    id: number;
    api_key: string;
};

export type CreateAppEnvItem = {
    slug: string;
    liveness_check_enabled?: boolean;
};

export type CreateAppRequestBody = {
    name: string;
    framework: string;
    envs: Array<CreateAppEnvItem>;
    target_response_time_ms?: number;
    team_id: number;
};

export type CreateAppResponse = {
    id: number;
    slug: string;
};

export type CreateConsumerGroupRequestBody = {
    name: string;
    consumer_ids: Array<number>;
};

export type CreateDismissalRequestBody = {
    key: string;
    scope: 'user' | 'team';
    team_id?: (number | null);
};

export namespace CreateDismissalRequestBody {
    export enum scope {
        USER = 'user',
        TEAM = 'team'
    }
}

export type CreateOrUpdateUserRequestBody = {
    locale?: (string | null);
    timezone?: (string | null);
};

export type CreateOrUpdateUserResponse = {
    user_id: number;
    onboarding_complete: boolean;
    site_admin: boolean;
    created_at: string;
};

export type CreateSavedFiltersRequestBody = {
    name: string;
    shared: boolean;
    filters: {
        [key: string]: (string | number | boolean | null);
    };
};

export type CreateTeamRequestBody = {
    name: string;
};

export type DataTransferredChartDataset = {
    time_windows: Array<string>;
    request_size_sums: Array<number>;
    response_size_sums: Array<number>;
};

export type ErrorRatesChartDataset = {
    error_type: 'Client error' | 'Server error';
    time_windows: Array<string>;
    error_rates: Array<number>;
};

export namespace ErrorRatesChartDataset {
    export enum error_type {
        CLIENT_ERROR = 'Client error',
        SERVER_ERROR = 'Server error'
    }
}

export type ErrorsByConsumerChartDataset = {
    consumer_ids: Array<number>;
    consumer_names: Array<string>;
    request_counts: Array<number>;
};

export type ErrorsChartDataset = {
    error_type: 'Client error' | 'Server error';
    time_windows: Array<string>;
    request_counts: Array<number>;
    status_code_counts: Array<Array<[
        number,
        number
    ]>>;
};

export namespace ErrorsChartDataset {
    export enum error_type {
        CLIENT_ERROR = 'Client error',
        SERVER_ERROR = 'Server error'
    }
}

export type ErrorsTableItem = {
    id: (number | null);
    method: string;
    path: string;
    status_code: number;
    status_text: string;
    request_count: number;
    affected_consumers: number;
    expected: boolean;
};

export type GeoIPResponse = {
    country_code: (string | null);
};

export type GetAlertRuleResponse = {
    id: number;
    name: string;
    description: (string | null);
    app: AlertRuleApp;
    app_env: AlertRuleAppEnv;
    metric: string;
    metric_name: string;
    metric_type: string;
    condition: string;
    condition_formatted: string;
    threshold: number;
    threshold_unit: (string | null);
    threshold_formatted: string;
    threshold_converted: number;
    period_minutes: number;
    frequency_minutes: (number | null);
    cron_expression: (string | null);
    timezone: (string | null);
    notify_triggered_after_minutes: number;
    notify_resolved_after_minutes: number;
    filter_consumer: (AlertFilterItem | null);
    filter_consumer_group: (AlertFilterItem | null);
    filter_method: (string | null);
    filter_path: (string | null);
    filter_status_code: (string | null);
    state: 'ok' | 'triggered' | 'pending' | 'disabled' | 'no_data' | 'error';
    muted: boolean;
    last_check_value: (number | null);
    last_checked_at: (string | null);
    last_triggered_at: (string | null);
};

export namespace GetAlertRuleResponse {
    export enum state {
        OK = 'ok',
        TRIGGERED = 'triggered',
        PENDING = 'pending',
        DISABLED = 'disabled',
        NO_DATA = 'no_data',
        ERROR = 'error'
    }
}

export type GetAppMetricsResponse = {
    request_count: number;
    error_rate: number;
    apdex_score: number;
    consumer_count: number;
    instance_count: number;
    alert_count: number;
};

export type GetAppResponse = {
    id: number;
    name: string;
    slug: string;
    client_id: string;
    framework: string;
    serverless: boolean;
    envs: Array<AppEnvItem>;
    target_response_time_ms: number;
    created_at: string;
    suspended: boolean;
    suspended_reasons: Array<string>;
};

export type GetConsumerGroupResponse = {
    id: number;
    name: string;
    consumers: Array<ConsumersItem>;
};

export type GetConsumerMetricsResponse = {
    total_consumers: number;
    new_consumers: number;
};

export type GetConsumersResponse = {
    id: number;
    identifier: string;
    name: string;
    hidden: boolean;
    group: (ConsumerGroupItem | null);
};

export type GetEndpointConfigResponse = {
    excluded: boolean;
    target_response_time_ms: (number | null);
};

export type GetEndpointResponse = {
    id: number;
    method: string;
    path: string;
    summary: (string | null);
    description: (string | null);
    target_response_time_ms: number;
    excluded: boolean;
};

export type GetErrorDetailsResponse = {
    request_count: number;
    affected_consumers: number;
    last_timestamp: string;
};

export type GetErrorsMetricsResponse = {
    total_request_count: number;
    total_error_count: number;
    client_error_count: number;
    server_error_count: number;
    error_rate: number;
};

export type GetMfaEnrollmentResponse = {
    enrolled: boolean;
};

export type GetPerformanceMetricsResponse = {
    total_request_count: number;
    apdex_satisfied_count: number;
    apdex_tolerated_count: number;
    apdex_frustrated_count: number;
    apdex_score: number;
    target_response_time_ms: number;
    response_time_p50: number;
    response_time_p75: number;
    response_time_p95: number;
};

export type GetStatusCodeCountsResponseItem = {
    method: string;
    path: string;
    status_code: number;
    description: (string | null);
    request_count: number;
    expected: boolean;
};

export type GetTeamDetailsAdminResponse = {
    id: number;
    name: string;
    apps: Array<TeamDetailsApp>;
    users: Array<TeamDetailsUser>;
    subscriptions: Array<TeamDetailsSubscription>;
    audit_log: Array<TeamDetailsAuditLogRecord>;
    login_history: HistoryChartDataset;
};

export type GetTeamIntegrationsResponse = {
    slack?: (TeamSlackIntegrationItem | null);
    microsoft_teams: (TeamMicrosoftTeamsIntegrationItem | null);
    sentry: (TeamSentryIntegrationItem | null);
};

export type GetTeamPlanResponse = {
    plan: (TeamPlan | null);
    subscription: (TeamSubscription | null);
    limits: TeamPlanLimits;
    limits_status: ('ok' | 'grace' | 'exceeded' | null);
    limits_grace_period_ends_at: (string | null);
    limits_last_checked_at: (string | null);
    quotas: TeamPlanQuotas;
    allow_quota_overage: boolean;
    features: TeamPlanFeatures;
};

export type GetTeamResponse = {
    id: number;
    name: string;
    slug: string;
    demo: boolean;
    users: Array<TeamUserItem>;
    invites: Array<TeamInviteItem>;
};

export type GetTrafficMetricsResponse = {
    total_request_count: number;
    requests_per_minute: number;
    client_error_count: number;
    server_error_count: number;
    error_rate: number;
    request_size_sum: number;
    request_size_avg: (number | null);
    response_size_sum: number;
    response_size_avg: (number | null);
    total_data_transferred: number;
    unique_consumer_count: number;
};

export type GetTrialAdminResponse = {
    status: string;
    ends_at: (string | null);
};

export type GetUserTeamSettingsResponseItem = {
    team_id: number;
    alert_emails_enabled: boolean;
};

export type HealthChecksTableResponseItem = {
    first_timestamp: string;
    last_timestamp: string;
    success: boolean;
    status_code: number;
    error: string;
    count: number;
};

export type HistogramDataset = {
    bins: Array<number>;
    counts: Array<number>;
    bin_size: number;
};

export type HistoryChartDataset = {
    days: Array<string>;
    counts: Array<number>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InviteUserRequestBody = {
    email: string;
    role: 'member' | 'admin' | 'owner';
};

export namespace InviteUserRequestBody {
    export enum role {
        MEMBER = 'member',
        ADMIN = 'admin',
        OWNER = 'owner'
    }
}

export type JoinTeamStealthRequestBody = {
    team_id: number;
};

export type ListAlertRulesResponseItem = {
    id?: (number | null);
    type: string;
    name: string;
    description?: (string | null);
    trigger?: (string | null);
    period_minutes?: (number | null);
    filters?: (AlertRuleFilters | null);
    app: AlertRuleApp;
    app_env: AlertRuleAppEnv;
    state: 'ok' | 'triggered' | 'pending' | 'disabled' | 'no_data' | 'error';
    muted: boolean;
    last_checked_at?: (string | null);
    last_triggered_at?: (string | null);
};

export namespace ListAlertRulesResponseItem {
    export enum state {
        OK = 'ok',
        TRIGGERED = 'triggered',
        PENDING = 'pending',
        DISABLED = 'disabled',
        NO_DATA = 'no_data',
        ERROR = 'error'
    }
}

export type ListAlertsResponseItem = {
    id: number;
    resolved: boolean;
    triggered_at: string;
    resolved_at: (string | null);
};

export type ListApiKeysResponseItem = {
    id: number;
    prefix: string;
    enabled: boolean;
    created_at: string;
    last_used_at: (string | null);
};

export type ListAppsResponseItem = {
    id: number;
    name: string;
    slug: string;
    client_id: string;
    framework: string;
    serverless: boolean;
    envs: Array<AppEnvItem>;
    target_response_time_ms: number;
    has_consumers: boolean;
    has_request_logs: boolean;
    created_at: string;
    suspended: boolean;
    suspended_reasons: Array<string>;
};

export type ListConsumerGroupsResponseItem = {
    id: number;
    name: string;
};

export type ListConsumerGroupsWithTrafficResponseItem = {
    id: number;
    name: string;
    consumers: number;
    requests: number;
    error_rate: (number | null);
    last_request_at: (string | null);
};

export type ListConsumersResponseItem = {
    id: number;
    identifier: string;
    name: string;
    group: (ConsumerGroupItem | null);
};

export type ListConsumersWithTrafficResponseItem = {
    id: number;
    identifier: string;
    name: string;
    group: (ConsumerGroupItem | null);
    requests: number;
    error_rate: number;
    first_request_at: string;
    last_request_at: string;
    is_new: boolean;
};

export type ListDismissalsResponseItem = {
    key: string;
    scope: 'user' | 'team';
};

export namespace ListDismissalsResponseItem {
    export enum scope {
        USER = 'user',
        TEAM = 'team'
    }
}

export type ListEndpointsResponseItem = {
    id: number;
    method: string;
    path: string;
    summary: (string | null);
    description: (string | null);
};

export type ListOveragesResponseItem = {
    type: string;
    prices: Array<OveragePrice>;
};

export type ListPlansResponseItem = {
    id: number;
    name: string;
    description: (string | null);
    limit_apps: (number | null);
    limit_users: (number | null);
    limit_instances: (number | null);
    limit_consumers: (number | null);
    limit_alert_rules: (number | null);
    monthly_request_log_quota: (number | null);
    monthly_application_log_quota: (number | null);
    monthly_span_quota: (number | null);
    allow_quota_overage: boolean;
    feature_health_checks: boolean;
    feature_chat_integration: boolean;
    feature_api_access: boolean;
    feature_data_export: boolean;
    prices: Array<PlanPrice>;
};

export type ListSavedFiltersResponseItem = {
    id: number;
    name: string;
    owned: boolean;
    shared: boolean;
    filters: {
        [key: string]: (string | number | boolean | null);
    };
};

export type ListTeamsAdminResponseItem = {
    id: number;
    name: string;
    plan: (TeamPlanAdmin | null);
    contact: (TeamContact | null);
    apps: Array<TeamApp>;
    user_count: number;
    last_login: (string | null);
    plan_limits_status: 'ok' | 'grace' | 'exceeded';
    plan_limits_grace_period_ends_at: (string | null);
    created_at: string;
};

export namespace ListTeamsAdminResponseItem {
    export enum plan_limits_status {
        OK = 'ok',
        GRACE = 'grace',
        EXCEEDED = 'exceeded'
    }
}

export type ListTeamsResponseItem = {
    id: number;
    name: string;
    slug: string;
    demo: boolean;
    role: string;
    stealth: boolean;
    apps_count: number;
    users_count: number;
};

export type MuteAlertRuleRequestBody = {
    muted: boolean;
};

export type OnboardUserRequestBody = {
    user_name?: (string | null);
    team_name?: (string | null);
    source?: (string | null);
    complete?: boolean;
};

export type OveragePrice = {
    currency: string;
    price: string;
    per_unit: number;
};

export type PerformanceEndpointsTableItem = {
    id: (number | null);
    method: string;
    path: string;
    total_request_count: number;
    apdex_satisfied_count: number;
    apdex_tolerated_count: number;
    apdex_frustrated_count: number;
    apdex_score: number;
    response_time_p50: number;
    response_time_p75: number;
    response_time_p95: number;
    target_response_time_ms: number;
    health_check: boolean;
    excluded: boolean;
    removed: boolean;
};

export type PlanPrice = {
    currency: string;
    interval: 'monthly' | 'yearly';
    price: string;
};

export namespace PlanPrice {
    export enum interval {
        MONTHLY = 'monthly',
        YEARLY = 'yearly'
    }
}

export type RequestLogItem = {
    timestamp: string;
    request_uuid: string;
    app_env: string;
    consumer_id: number;
    consumer_identifier: string;
    consumer_name: string;
    method: string;
    path: string;
    url: string;
    request_size: number;
    status_code: number;
    status_text: string;
    response_time: number;
    response_size: number;
    client_ip: string;
    client_country_name: string;
    client_country_iso_code: string;
    application_logs_count_by_level: {
        [key: string]: number;
    };
};

export type RequestLogItemDetails = {
    timestamp: string;
    request_uuid: string;
    app_env: string;
    consumer_id: number;
    consumer_identifier: string;
    consumer_name: string;
    method: string;
    path: string;
    url: string;
    request_size: number;
    status_code: number;
    status_text: string;
    response_time: number;
    response_size: number;
    client_ip: string;
    client_country_name: string;
    client_country_iso_code: string;
    application_logs_count_by_level: {
        [key: string]: number;
    };
    request_headers: Array<[
        string,
        string
    ]>;
    request_content_type: (string | null);
    request_body: string;
    response_headers: Array<[
        string,
        string
    ]>;
    response_content_type: (string | null);
    response_body: string;
    exception_type: string;
    exception_message: string;
    exception_stacktrace: string;
    sentry_event_id_captured: boolean;
    sentry_url: (string | null);
    application_logs_count: number;
    trace_id: (string | null);
    spans_count: number;
};

export type RequestLogTimelineChartDataset = {
    time_windows: Array<string>;
    item_counts: Array<number>;
};

export type RequestsByConsumerChartDataset = {
    response_status: 'Successful' | 'Client error' | 'Server error';
    consumer_ids: Array<number>;
    consumer_names: Array<string>;
    request_counts: Array<number>;
    status_code_counts: Array<Array<[
        number,
        number
    ]>>;
};

export namespace RequestsByConsumerChartDataset {
    export enum response_status {
        SUCCESSFUL = 'Successful',
        CLIENT_ERROR = 'Client error',
        SERVER_ERROR = 'Server error'
    }
}

export type RequestsChartDataset = {
    response_status: 'Successful' | 'Client error' | 'Server error';
    time_windows: Array<string>;
    request_counts: Array<number>;
    status_code_counts: Array<Array<[
        number,
        number
    ]>>;
};

export namespace RequestsChartDataset {
    export enum response_status {
        SUCCESSFUL = 'Successful',
        CLIENT_ERROR = 'Client error',
        SERVER_ERROR = 'Server error'
    }
}

export type RequestsPerMinuteChartDataset = {
    time_windows: Array<string>;
    requests_per_minute: Array<number>;
};

export type ResourcesMetrics = {
    app_env: string;
    cpu_percent_avg: number;
    cpu_percent_min: number;
    cpu_percent_max: number;
    memory_rss_avg: number;
    memory_rss_min: number;
    memory_rss_max: number;
};

export type ResponseTimeChartDataset = {
    percentile: 'p50' | 'p75' | 'p95';
    time_windows: Array<string>;
    response_times: Array<number>;
    total_request_counts: Array<number>;
};

export namespace ResponseTimeChartDataset {
    export enum percentile {
        P50 = 'p50',
        P75 = 'p75',
        P95 = 'p95'
    }
}

export type ResponseTimeHistogramDataset = {
    bins: Array<number>;
    counts: Array<number>;
    bin_size: number;
    outliers: ResponseTimeHistogramOutliers;
};

export type ResponseTimeHistogramOutliers = {
    min: (number | null);
    max: (number | null);
    count: number;
};

export type ServerErrorsTableItem = {
    type: string;
    msg: string;
    traceback: string;
    sentry_url: (string | null);
    sentry_event_id_captured: boolean;
    error_count: number;
};

export type SpanItem = {
    span_id: string;
    parent_span_id: (string | null);
    name: string;
    kind: string;
    start_time: number;
    end_time: number;
    status: string;
    attributes: {
        [key: string]: string;
    };
};

export type SubmitSupportRequestRequestBody = {
    message: string;
    team_id?: (number | null);
    account_deleted?: boolean;
};

export type TeamApp = {
    id: number;
    name: string;
    client_id: string;
    framework: string;
    envs: Array<TeamAppEnv>;
    online: boolean;
    suspended: boolean;
};

export type TeamAppEnv = {
    id: number;
    name: string;
    slug: string;
    online: boolean;
    last_sync_at: (string | null);
};

export type TeamContact = {
    name: string;
    email: string;
};

export type TeamDetailsApp = {
    id: number;
    name: string;
    framework: string;
    envs: Array<TeamDetailsAppEnv>;
    instance_count_history: (HistoryChartDataset | null);
    consumer_count_history: (HistoryChartDataset | null);
    logged_requests_history: (HistoryChartDataset | null);
    suspended: boolean;
};

export type TeamDetailsAppEnv = {
    id: number;
    name: string;
    slug: string;
    active: boolean;
    online: boolean;
    last_sync_at: (string | null);
    last_startup_at: (string | null);
    client: (string | null);
    versions: ({
    [key: string]: string;
} | null);
};

export type TeamDetailsAuditLogRecord = {
    id: number;
    user_id: (number | null);
    user_name: (string | null);
    app_id: (number | null);
    app_name: (string | null);
    action: string;
    details: ({
    [key: string]: unknown;
} | null);
    created_at: string;
};

export type TeamDetailsSubscription = {
    id: number;
    lmsqueezy_subscription_url: (string | null);
    stripe_subscription_url: (string | null);
    plan: string;
    status: string;
    currency: (string | null);
    interval: ('monthly' | 'yearly' | null);
    created_at: string;
    renews_at: (string | null);
    ends_at: (string | null);
};

export type TeamDetailsUser = {
    id: number;
    auth0_user_id: string;
    name: string;
    email: string;
    role: string;
    last_login_at: (string | null);
    timezone: (string | null);
    source: (string | null);
    suspended: boolean;
};

export type TeamInviteItem = {
    id: number;
    email: string;
    role: string;
    created_at: string;
    expires_at: string;
};

export type TeamMicrosoftTeamsIntegrationItem = {
    webhook_url: string;
};

export type TeamPlan = {
    id: number;
    name: string;
    trial: boolean;
    upgradable: boolean;
    allow_quota_overage: boolean;
    custom: boolean;
};

export type TeamPlanAdmin = {
    name: string;
    trial: boolean;
    paid: boolean;
    canceled: (boolean | null);
    subscription_status: (string | null);
    subscription_ends_at: (string | null);
};

export type TeamPlanFeatures = {
    health_checks: boolean;
    chat_integration: boolean;
    data_export: boolean;
    api_access: boolean;
    security_enforcement: boolean;
};

export type TeamPlanLimits = {
    apps: TeamPlanLimitsItem;
    users: TeamPlanLimitsItem;
    instances: TeamPlanLimitsItem;
    consumers: TeamPlanLimitsItem;
    alert_rules: TeamPlanLimitsItem;
};

export type TeamPlanLimitsItem = {
    actual: number;
    allowed: (number | null);
};

export type TeamPlanQuotaItem = {
    quota: (number | null);
    percent_used: number;
    status: 'ok' | 'exceeded' | 'disabled';
};

export namespace TeamPlanQuotaItem {
    export enum status {
        OK = 'ok',
        EXCEEDED = 'exceeded',
        DISABLED = 'disabled'
    }
}

export type TeamPlanQuotas = {
    request_logs: TeamPlanQuotaItem;
    application_logs: TeamPlanQuotaItem;
    spans: TeamPlanQuotaItem;
};

export type TeamSentryIntegrationItem = {
    org: string;
};

export type TeamSettings = {
    allow_quota_overage: boolean;
    require_mfa: boolean;
};

export type TeamSlackIntegrationItem = {
    team: string;
    channel: string;
    configuration_url: string;
};

export type TeamSubscription = {
    payment_platform: (string | null);
    status: string;
    currency: (string | null);
    interval: ('monthly' | 'yearly' | null);
    renews_at: (string | null);
    ends_at: (string | null);
    past_due_since: (string | null);
};

export type TeamUserItem = {
    id: number;
    name: string;
    email: string;
    email_verified: boolean;
    invite_email: (string | null);
    role: string;
    mfa_enrolled: (boolean | null);
    last_login_at: string;
    member_since: string;
    suspended: boolean;
};

export type TrafficEndpointsTableItem = {
    id: (number | null);
    method: string;
    path: string;
    total_request_count: number;
    client_error_count: number;
    server_error_count: number;
    error_rate: number;
    data_transferred: number;
    health_check: boolean;
    excluded: boolean;
    removed: boolean;
};

export type UpdateAlertRuleRequestBody = {
    name: string;
    description?: (string | null);
    metric: string;
    condition: string;
    threshold: number;
    threshold_unit?: (string | null);
    period_minutes: number;
    frequency_minutes?: (number | null);
    cron_expression?: (string | null);
    timezone?: (string | null);
    notify_triggered_after_minutes?: number;
    notify_resolved_after_minutes?: number;
    filter_consumer_id?: (number | null);
    filter_consumer_group_id?: (number | null);
    filter_method?: (string | null);
    filter_path?: (string | null);
    filter_status_code?: (string | null);
};

export type UpdateAppEnvRequestBody = {
    liveness_check_enabled?: (boolean | null);
    liveness_check_muted?: (boolean | null);
    health_check_enabled?: (boolean | null);
    health_check_muted?: (boolean | null);
    health_check_url?: (string | null);
};

export type UpdateAppRequestBody = {
    name: string;
    framework: string;
    envs: Array<CreateAppEnvItem>;
    target_response_time_ms?: number;
};

export type UpdateConsumerGroupRequestBody = {
    name: string;
    consumer_ids?: (Array<number> | null);
};

export type UpdateConsumerRequestBody = {
    name: string;
    consumer_group_id?: (number | null);
};

export type UpdateEndpointConfigRequestBody = {
    method: string;
    path: string;
    excluded: boolean;
    target_response_time_ms?: (number | null);
};

export type UpdateEndpointErrorConfigRequestBody = {
    method: string;
    path: string;
    status_code: number;
    expected: boolean;
};

export type UpdateOveragesRequestBody = {
    enabled: boolean;
};

export type UpdateProfileRequestBody = {
    name: string;
    email: string;
};

export type UpdateRequireMfaRequestBody = {
    enabled: boolean;
};

export type UpdateSavedFiltersRequestBody = {
    name?: (string | null);
    shared?: (boolean | null);
};

export type UpdateTeamRequestBody = {
    name: string;
};

export type UpdateTeamUserRequestBody = {
    role: 'member' | 'admin' | 'owner';
};

export namespace UpdateTeamUserRequestBody {
    export enum role {
        MEMBER = 'member',
        ADMIN = 'admin',
        OWNER = 'owner'
    }
}

export type UpdateTrialAdminRequestBody = {
    ends_at: string;
};

export type UpdateUserTeamSettingsRequestBody = {
    alert_emails_enabled?: (boolean | null);
};

export type UptimeChartsResponse = {
    time_windows: Array<string>;
    apps: {
        [key: string]: {
            [key: string]: Array<UptimeChartsResponseItem>;
        };
    };
};

export type UptimeChartsResponseItem = {
    uptime: UptimeStatus;
    health_checks: UptimeStatus;
};

export type UptimePercentages = {
    uptime: number;
    healthy: number;
};

export type UptimeStatus = {
    status: (boolean | null);
    success_count: number;
    total_count: number;
    errors?: (Array<string> | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ValidationErrorsTableItem = {
    loc: Array<string>;
    msg: string;
    type: string;
    error_count: number;
};

export type ListTeamsAdminData = {
    filter?: (string | null);
};

export type ListTeamsAdminResponse = (Array<ListTeamsAdminResponseItem>);

export type GetTeamDetailsAdminData = {
    teamId: number;
};

export type GetTeamDetailsAdminResponse2 = (GetTeamDetailsAdminResponse);

export type DeleteTeamAdminData = {
    teamId: number;
};

export type DeleteTeamAdminResponse = (void);

export type GetTrialAdminData = {
    teamId: number;
};

export type GetTrialAdminResponse2 = ((GetTrialAdminResponse | null));

export type UpdateTrialAdminData = {
    requestBody: UpdateTrialAdminRequestBody;
    teamId: number;
};

export type UpdateTrialAdminResponse = (void);

export type TriggerUsageChecksAdminData = {
    teamId: number;
};

export type TriggerUsageChecksAdminResponse = (void);

export type GetAlertCountData = {
    teamId: number;
};

export type GetAlertCountResponse = (number);

export type ListAlertsData = {
    appEnvId: number;
    appId: number;
    type: string;
};

export type ListAlertsResponse = (Array<ListAlertsResponseItem>);

export type ListAlertRulesData = {
    teamId: number;
};

export type ListAlertRulesResponse = (Array<ListAlertRulesResponseItem>);

export type CreateAlertRuleData = {
    requestBody: CreateAlertRuleRequestBody;
};

export type CreateAlertRuleResponse2 = (CreateAlertRuleResponse);

export type GetAlertRuleData = {
    alertRuleId: number;
};

export type GetAlertRuleResponse2 = (GetAlertRuleResponse);

export type UpdateAlertRuleData = {
    alertRuleId: number;
    requestBody: (UpdateAlertRuleRequestBody | MuteAlertRuleRequestBody);
};

export type UpdateAlertRuleResponse = (void);

export type DeleteAlertRuleData = {
    alertRuleId: number;
};

export type DeleteAlertRuleResponse = (void);

export type CheckAlertRuleData = {
    alertRuleId: number;
};

export type CheckAlertRuleResponse = (void);

export type GetAlertRuleTimelineChartData = {
    alertRuleId: number;
};

export type GetAlertRuleTimelineChartResponse = (AlertRuleTimelineChartDataset);

export type ListAnnouncementsResponse = (Array<AnnouncementResponseItem>);

export type ListAppsData = {
    teamId: number;
};

export type ListAppsResponse = (Array<ListAppsResponseItem>);

export type CreateAppData = {
    requestBody: CreateAppRequestBody;
};

export type CreateAppResponse2 = (CreateAppResponse);

export type GetAppData = {
    appId: number;
};

export type GetAppResponse2 = (GetAppResponse);

export type UpdateAppData = {
    appId: number;
    requestBody: UpdateAppRequestBody;
};

export type UpdateAppResponse = (void);

export type DeleteAppData = {
    appId: number;
};

export type DeleteAppResponse = (void);

export type UpdateAppEnvData = {
    appEnvId: number;
    appId: number;
    requestBody: UpdateAppEnvRequestBody;
};

export type UpdateAppEnvResponse = (void);

export type GetAppMetricsData = {
    appEnv?: (string | null);
    appId: number;
    period?: string;
};

export type GetAppMetricsResponse2 = (GetAppMetricsResponse);

export type ListPlansResponse = (Array<ListPlansResponseItem>);

export type ListOveragesResponse = (Array<ListOveragesResponseItem>);

export type ListConsumersData = {
    appEnv?: (string | null);
    appId: number;
};

export type ListConsumersResponse = (Array<ListConsumersResponseItem>);

export type ListConsumersWithTrafficData = {
    appEnv?: (string | null);
    appId: number;
    period?: string;
};

export type ListConsumersWithTrafficResponse = (Array<ListConsumersWithTrafficResponseItem>);

export type GetConsumerMetricsData = {
    appEnv?: (string | null);
    appId: number;
    period?: string;
};

export type GetConsumerMetricsResponse2 = (GetConsumerMetricsResponse);

export type GetConsumerData = {
    appId: number;
    consumerId: number;
};

export type GetConsumerResponse = (GetConsumersResponse);

export type UpdateConsumerData = {
    appId: number;
    consumerId: number;
    requestBody: UpdateConsumerRequestBody;
};

export type UpdateConsumerResponse = (void);

export type GetConsumersChartData = {
    appEnv?: (string | null);
    appId: number;
    period?: string;
};

export type GetConsumersChartResponse = (Array<ConsumersChartDataset>);

export type ListConsumerGroupsData = {
    appEnv?: (string | null);
    appId: number;
};

export type ListConsumerGroupsResponse = (Array<ListConsumerGroupsResponseItem>);

export type CreateConsumerGroupData = {
    appId: number;
    requestBody: CreateConsumerGroupRequestBody;
};

export type CreateConsumerGroupResponse = (number);

export type ListConsumerGroupsWithTrafficData = {
    appEnv?: (string | null);
    appId: number;
    period?: string;
};

export type ListConsumerGroupsWithTrafficResponse = (Array<ListConsumerGroupsWithTrafficResponseItem>);

export type GetConsumerGroupData = {
    appId: number;
    consumerGroupId: number;
};

export type GetConsumerGroupResponse2 = (GetConsumerGroupResponse);

export type UpdateConsumerGroupData = {
    appId: number;
    consumerGroupId: number;
    requestBody: UpdateConsumerGroupRequestBody;
};

export type UpdateConsumerGroupResponse = (void);

export type DeleteConsumerGroupData = {
    appId: number;
    consumerGroupId: number;
};

export type DeleteConsumerGroupResponse = (void);

export type SlackInteractionResponse = (void);

export type HealthCheckResponse = (void);

export type ListDismissalsData = {
    teamId: number;
};

export type ListDismissalsResponse = (Array<ListDismissalsResponseItem>);

export type CreateDismissalData = {
    requestBody: CreateDismissalRequestBody;
};

export type CreateDismissalResponse = (unknown);

export type GetEndpointConfigData = {
    appId: number;
    method: string;
    path: string;
};

export type GetEndpointConfigResponse2 = (GetEndpointConfigResponse);

export type UpdateEndpointConfigData = {
    appId: number;
    requestBody: UpdateEndpointConfigRequestBody;
};

export type UpdateEndpointConfigResponse = (void);

export type UpdateEndpointErrorConfigData = {
    appId: number;
    requestBody: UpdateEndpointErrorConfigRequestBody;
};

export type UpdateEndpointErrorConfigResponse = (void);

export type ListEndpointsData = {
    appEnvId?: (number | null);
    appId: number;
};

export type ListEndpointsResponse = (Array<ListEndpointsResponseItem>);

export type GetEndpointData = {
    appId: number;
    endpointId: number;
};

export type GetEndpointResponse2 = (GetEndpointResponse);

export type GetErrorsMetricsData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorsMetricsResponse2 = (GetErrorsMetricsResponse);

export type GetErrorsChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorsChartResponse = (Array<ErrorsChartDataset>);

export type GetErrorsByConsumerChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorsByConsumerChartResponse = (ErrorsByConsumerChartDataset);

export type GetErrorRatesChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorRatesChartResponse = (Array<ErrorRatesChartDataset>);

export type GetErrorsTableData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorsTableResponse = (Array<ErrorsTableItem>);

export type GetErrorDetailsData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetErrorDetailsResponse2 = (GetErrorDetailsResponse);

export type GetValidationErrorsTableData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    limit?: number;
    method: string;
    path: string;
    period?: string;
};

export type GetValidationErrorsTableResponse = (Array<ValidationErrorsTableItem>);

export type GetServerErrorsTableData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    limit?: number;
    method: string;
    path: string;
    period?: string;
};

export type GetServerErrorsTableResponse = (Array<ServerErrorsTableItem>);

export type GetCountryResponse = (GeoIPResponse);

export type GetPerformanceMetricsData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetPerformanceMetricsResponse2 = (GetPerformanceMetricsResponse);

export type GetPerformanceEndpointsTableData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetPerformanceEndpointsTableResponse = (Array<PerformanceEndpointsTableItem>);

export type GetApdexScoreChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetApdexScoreChartResponse = (ApdexScoreChartDataset);

export type GetResponseTimeChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetResponseTimeChartResponse = (Array<ResponseTimeChartDataset>);

export type GetResponseTimeHistogramData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetResponseTimeHistogramResponse = (ResponseTimeHistogramDataset);

export type GetRequestLogsData = {
    appEnv?: (string | null);
    appId: number;
    clientIp?: (string | null);
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    limit?: number;
    logLevel?: (string | null);
    maxRequestSize?: (number | null);
    maxResponseSize?: (number | null);
    maxResponseTime?: (number | null);
    maxTimestamp?: (string | null);
    method?: (string | null);
    minRequestSize?: (number | null);
    minResponseSize?: (number | null);
    minResponseTime?: (number | null);
    minTimestamp?: (string | null);
    order?: 'asc' | 'desc';
    page?: number;
    path?: (string | null);
    pathExact?: boolean;
    period?: (string | null);
    requestBody?: (string | null);
    responseBody?: (string | null);
    statusCode?: (number | string | null);
    url?: (string | null);
};

export type GetRequestLogsResponse = (Array<RequestLogItem>);

export type GetRequestLogsTimelineData = {
    appEnv?: (string | null);
    appId: number;
    clientIp?: (string | null);
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    logLevel?: (string | null);
    maxRequestSize?: (number | null);
    maxResponseSize?: (number | null);
    maxResponseTime?: (number | null);
    method?: (string | null);
    minRequestSize?: (number | null);
    minResponseSize?: (number | null);
    minResponseTime?: (number | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    requestBody?: (string | null);
    responseBody?: (string | null);
    statusCode?: (number | string | null);
    url?: (string | null);
};

export type GetRequestLogsTimelineResponse = (RequestLogTimelineChartDataset);

export type ExportRequestLogsCsvData = {
    appEnv?: (string | null);
    appId: number;
    clientIp?: (string | null);
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    logLevel?: (string | null);
    maxRequestSize?: (number | null);
    maxResponseSize?: (number | null);
    maxResponseTime?: (number | null);
    method?: (string | null);
    minRequestSize?: (number | null);
    minResponseSize?: (number | null);
    minResponseTime?: (number | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    requestBody?: (string | null);
    responseBody?: (string | null);
    statusCode?: (number | string | null);
    url?: (string | null);
};

export type ExportRequestLogsCsvResponse = (string);

export type GetRequestLogItemDetailsData = {
    appId: number;
    requestUuid: string;
};

export type GetRequestLogItemDetailsResponse = (RequestLogItemDetails);

export type GetRequestLogItemLogsData = {
    appId: number;
    requestUuid: string;
};

export type GetRequestLogItemLogsResponse = (Array<ApplicationLogItem>);

export type GetRequestLogItemSpansData = {
    appId: number;
    requestUuid: string;
};

export type GetRequestLogItemSpansResponse = (Array<SpanItem>);

export type GetCpuMemoryChartData = {
    appEnv: string;
    appId: number;
    period?: string;
};

export type GetCpuMemoryChartResponse = (CPUMemoryChartDataset);

export type GetResourcesMetricsData = {
    appId: number;
};

export type GetResourcesMetricsResponse = (Array<ResourcesMetrics>);

export type ListSavedFiltersData = {
    appId: number;
};

export type ListSavedFiltersResponse = (Array<ListSavedFiltersResponseItem>);

export type CreateSavedFiltersData = {
    appId: number;
    requestBody: CreateSavedFiltersRequestBody;
};

export type CreateSavedFiltersResponse = (unknown);

export type UpdateSavedFiltersData = {
    appId: number;
    requestBody: UpdateSavedFiltersRequestBody;
    savedFiltersId: number;
};

export type UpdateSavedFiltersResponse = (void);

export type DeleteSavedFiltersData = {
    appId: number;
    savedFiltersId: number;
};

export type DeleteSavedFiltersResponse = (void);

export type CreateCheckoutSessionData = {
    billingInterval?: 'monthly' | 'yearly';
    currency?: string;
    planId: number;
    teamId: number;
};

export type CreateCheckoutSessionResponse = (string);

export type CreateCustomerPortalSessionData = {
    billingInterval?: ('monthly' | 'yearly' | null);
    currency?: string;
    flowType?: ('subscription_update_confirm' | 'payment_method_update' | null);
    planId?: (number | null);
    teamId: number;
};

export type CreateCustomerPortalSessionResponse = (string);

export type HandleStripeWebhookResponse = (void);

export type SubmitSupportRequestData = {
    requestBody: SubmitSupportRequestRequestBody;
};

export type SubmitSupportRequestResponse = (void);

export type ListTeamsResponse = (Array<ListTeamsResponseItem>);

export type CreateTeamData = {
    requestBody: CreateTeamRequestBody;
};

export type CreateTeamResponse = (number);

export type GetTeamData = {
    teamId: number;
};

export type GetTeamResponse2 = (GetTeamResponse);

export type UpdateTeamData = {
    requestBody: UpdateTeamRequestBody;
    teamId: number;
};

export type UpdateTeamResponse = (void);

export type DeleteTeamData = {
    teamId: number;
};

export type DeleteTeamResponse = (void);

export type GetTeamPlanData = {
    teamId: number;
};

export type GetTeamPlanResponse2 = (GetTeamPlanResponse);

export type UpdateTeamUserData = {
    requestBody: UpdateTeamUserRequestBody;
    teamId: number;
    userId: number;
};

export type UpdateTeamUserResponse = (void);

export type RemoveUserFromTeamData = {
    teamId: number;
    userId: number;
};

export type RemoveUserFromTeamResponse = (void);

export type InviteUserData = {
    requestBody: InviteUserRequestBody;
    teamId: number;
};

export type InviteUserResponse = (number);

export type ResendInviteData = {
    inviteId: number;
    teamId: number;
};

export type ResendInviteResponse = (void);

export type UpdateInviteData = {
    inviteId: number;
    requestBody: UpdateTeamUserRequestBody;
    teamId: number;
};

export type UpdateInviteResponse = (void);

export type CancelInviteData = {
    inviteId: number;
    teamId: number;
};

export type CancelInviteResponse = (void);

export type AcceptInviteData = {
    code: string;
};

export type AcceptInviteResponse = (number);

export type GetTeamIntegrationsData = {
    teamId: number;
};

export type GetTeamIntegrationsResponse2 = (GetTeamIntegrationsResponse);

export type ConfigureSlackIntegrationData = {
    requestBody: string;
    teamId: number;
};

export type ConfigureSlackIntegrationResponse = (void);

export type DeleteSlackIntegrationData = {
    teamId: number;
};

export type DeleteSlackIntegrationResponse = (void);

export type TestSlackIntegrationData = {
    teamId: number;
};

export type TestSlackIntegrationResponse = (void);

export type ConfigureMicrosoftTeamsIntegrationData = {
    requestBody: ConfigureMicrosoftTeamsIntegrationRequestBody;
    teamId: number;
};

export type ConfigureMicrosoftTeamsIntegrationResponse = (void);

export type DeleteMicrosoftTeamsIntegrationData = {
    teamId: number;
};

export type DeleteMicrosoftTeamsIntegrationResponse = (void);

export type TestMicrosoftTeamsIntegrationData = {
    teamId: number;
};

export type TestMicrosoftTeamsIntegrationResponse = (void);

export type ConfigureSentryIntegrationData = {
    requestBody: ConfigureSentryIntegrationRequestBody;
    teamId: number;
};

export type ConfigureSentryIntegrationResponse = (void);

export type ListApiKeysData = {
    teamId: number;
};

export type ListApiKeysResponse = (Array<ListApiKeysResponseItem>);

export type CreateApiKeyData = {
    teamId: number;
};

export type CreateApiKeyResponse2 = (CreateApiKeyResponse);

export type DeleteApiKeyData = {
    apiKeyId: number;
    teamId: number;
};

export type DeleteApiKeyResponse = (void);

export type GetTeamSettingsData = {
    teamId: number;
};

export type GetTeamSettingsResponse = (TeamSettings);

export type UpdateAllowQuotaOveragesData = {
    requestBody: UpdateOveragesRequestBody;
    teamId: number;
};

export type UpdateAllowQuotaOveragesResponse = (void);

export type UpdateRequireMfaData = {
    requestBody: UpdateRequireMfaRequestBody;
    teamId: number;
};

export type UpdateRequireMfaResponse = (void);

export type GetConsumerRequestsSparklinesData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    groups?: boolean;
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetConsumerRequestsSparklinesResponse = ({
    [key: string]: Array<number>;
});

export type GetTrafficMetricsData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetTrafficMetricsResponse2 = (GetTrafficMetricsResponse);

export type GetRequestsChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetRequestsChartResponse = (Array<RequestsChartDataset>);

export type GetRequestsPerMinuteChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetRequestsPerMinuteChartResponse = (RequestsPerMinuteChartDataset);

export type GetDataTransferredChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetDataTransferredChartResponse = (DataTransferredChartDataset);

export type GetRequestsByConsumerChartData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    limit?: number;
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetRequestsByConsumerChartResponse = (Array<RequestsByConsumerChartDataset>);

export type GetRequestSizeHistogramData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetRequestSizeHistogramResponse = (HistogramDataset);

export type GetResponseSizeHistogramData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetResponseSizeHistogramResponse = (HistogramDataset);

export type GetTrafficEndpointsTableData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetTrafficEndpointsTableResponse = (Array<TrafficEndpointsTableItem>);

export type GetStatusCodeCountsData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type GetStatusCodeCountsResponse = (Array<GetStatusCodeCountsResponseItem>);

export type ListStatusCodesData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type ListStatusCodesResponse = (Array<number>);

export type ExportTrafficCsvData = {
    appEnv?: (string | null);
    appId: number;
    consumerGroupId?: (number | null);
    consumerId?: (number | null);
    groupBy?: Array<'endpoint' | 'consumer' | 'status_code'>;
    intervals?: 'hours' | 'days' | 'months';
    method?: (string | null);
    path?: (string | null);
    pathExact?: boolean;
    period?: string;
    statusCode?: (number | string | null);
};

export type ExportTrafficCsvResponse = (string);

export type GetUptimePercentagesData = {
    period?: string;
    teamId: number;
};

export type GetUptimePercentagesResponse = ({
    [key: string]: {
        [key: string]: UptimePercentages;
    };
});

export type GetUptimeChartsData = {
    period?: string;
    teamId: number;
};

export type GetUptimeChartsResponse = (UptimeChartsResponse);

export type GetHealthChecksTableData = {
    appEnv: string;
    appId: number;
    period?: string;
};

export type GetHealthChecksTableResponse = (Array<HealthChecksTableResponseItem>);

export type CreateOrUpdateUserData = {
    requestBody: CreateOrUpdateUserRequestBody;
};

export type CreateOrUpdateUserResponse2 = (CreateOrUpdateUserResponse);

export type DeleteUserResponse = (void);

export type OnboardUserData = {
    requestBody: OnboardUserRequestBody;
};

export type OnboardUserResponse = (void);

export type JoinTeamStealthData = {
    requestBody: JoinTeamStealthRequestBody;
};

export type JoinTeamStealthResponse = (void);

export type JoinDemoTeamResponse = (void);

export type UpdateUserTeamSettingsData = {
    requestBody: UpdateUserTeamSettingsRequestBody;
    teamId: number;
};

export type UpdateUserTeamSettingsResponse = (void);

export type LeaveTeamData = {
    teamId: number;
};

export type LeaveTeamResponse = (void);

export type GetUserTeamSettingsResponse = (Array<GetUserTeamSettingsResponseItem>);

export type UpdateProfileData = {
    requestBody: UpdateProfileRequestBody;
};

export type UpdateProfileResponse = (void);

export type CreatePasswordChangeTicketResponse = (string);

export type SendVerificationEmailResponse = (void);

export type GetMfaEnrollmentResponse2 = (GetMfaEnrollmentResponse);

export type CreateMfaEnrollmentTicketResponse = (string);

export type DeleteMfaEnrollmentResponse = (void);